export const GET_ALL_ALERTS = 'CVO/ALERTS/GET_ALL_ALERTS';
export const GET_ALL_ALERTS_SUCCESS = 'CVO/ALERTS/GET_ALL_ALERTS_SUCCESS';
export const GET_ALL_ALERTS_ERROR = 'CVO/ALERTS/GET_ALL_ALERTS_ERROR';

export const FETCH_ALERT = 'CVO/ALERTS/FETCH_ALERT';
export const FETCH_ALERT_SUCCESS = 'CVO/ALERTS/FETCH_ALERT_SUCCESS';
export const FETCH_ALERT_ERROR = 'CVO/ALERTS/FETCH_ALERT_ERROR';

export const PATCH_ALERT = 'CVO/ALERTS/PATCH_ALERT';
export const PATCH_ALERT_SUCCESS = 'CVO/ALERTS/PATCH_ALERT_SUCCESS';
export const PATCH_ALERT_ERROR = 'CVO/ALERTS/PATCH_ALERT_ERROR';

export const API_ALERT = '/api/alerts/';

export const API_ESCALATION_RULE = 'api/alert-escalation-rules/';

export const FETCH_ALL_ESCALATION_RULES = 'CVO/ALERTS/FETCH_ALL_ESCALATION_RULES';
export const FETCH_ALL_ESCALATION_RULES_SUCCESS = 'CVO/ALERTS/FETCH_ALL_ESCALATION_RULES_SUCCESS';
export const FETCH_ALL_ESCALATION_RULES_ERROR = 'CVO/ALERTS/FETCH_ALL_ESCALATION_RULES_ERROR';

export const PATCH_ESCALATION_RULE = 'CVO/ALERTS/PATCH_ESCALATION_RULE';
export const PATCH_ESCALATION_RULE_SUCCESS = 'CVO/ALERTS/PATCH_ESCALATION_RULE_SUCCESS';
export const PATCH_ESCALATION_RULE_ERROR = 'CVO/ALERTS/PATCH_ESCALATION_RULE_ERROR';

export const AUDIO_LINK = 'https://s3.eu-central-1.amazonaws.com/ltg-test/1097.wav';