export const FETCH_ASSETS = 'CVO/ASSETS/FETCH_ASSETS';
export const FETCH_ASSETS_SUCCESS = 'CVO/ASSETS/FETCH_ASSETS_SUCCESS';
export const FETCH_ASSETS_ERROR = 'CVO/ASSETS/FETCH_ASSETS_ERROR';

export const FETCH_ASSET = 'CVO/ASSETS/FETCH_ASSET';
export const FETCH_ASSET_SUCCESS = 'CVO/ASSETS/FETCH_ASSET_SUCCESS';
export const FETCH_ASSET_ERROR = 'CVO/ASSETS/FETCH_ASSET_ERROR';

export const ADD_ASSET = 'CVO/ASSETS/ADD_ASSET';
export const ADD_ASSET_SUCCESS = 'CVO/ASSETS/ADD_ASSET_SUCCESS';
export const ADD_ASSET_ERROR = 'CVO/ASSETS/ADD_ASSET_ERROR';

export const PATCH_ASSET = 'CVO/ASSETS/PATCH_ASSET';
export const PATCH_ASSET_SUCCESS = 'CVO/ASSETS/PATCH_ASSET_SUCCESS';
export const PATCH_ASSET_ERROR = 'CVO/ASSETS/PATCH_ASSET_ERROR';

export const DELETE_ASSET = 'CVO/ASSETS/DELETE_ASSET';
export const DELETE_ASSET_SUCCESS = 'CVO/ASSETS/DELETE_ASSET_SUCCESS';
export const DELETE_ASSET_ERROR = 'CVO/ASSETS/DELETE_ASSET_ERROR';

export const PATCH_ASSET_GROUPS = 'CVO/ASSETS/PATCH_ASSET_GROUPS';
export const PATCH_ASSET_GROUPS_SUCCESS = 'CVO/ASSETS/PATCH_ASSET_GROUPS_SUCCESS';
export const PATCH_ASSET_GROUPS_ERROR = 'CVO/ASSETS/PATCH_ASSET_GROUPS_ERROR';