export const FETCH_PERSONS = 'CVO/PERSONS/FETCH_PERSONS';
export const FETCH_PERSONS_SUCCESS = 'CVO/PERSONS/FETCH_PERSONS_SUCCESS';
export const FETCH_PERSONS_ERROR = 'CVO/PERSONS/FETCH_PERSONS_ERROR';

export const FETCH_PERSON = 'CVO/PERSONS/FETCH_PERSON';
export const FETCH_PERSON_SUCCESS = 'CVO/PERSONS/FETCH_PERSON_SUCCESS';
export const FETCH_PERSON_ERROR = 'CVO/PERSONS/FETCH_PERSON_ERROR';

export const ADD_PERSON = 'CVO/PERSONS/ADD_PERSON';
export const ADD_PERSON_SUCCESS = 'CVO/PERSONS/ADD_PERSON_SUCCESS';
export const ADD_PERSON_ERROR = 'CVO/PERSONS/ADD_PERSON_ERROR';

export const PATCH_PERSON = 'CVO/PERSONS/PATCH_PERSON';
export const PATCH_PERSON_SUCCESS = 'CVO/PERSONS/PATCH_PERSON_SUCCESS';
export const PATCH_PERSON_ERROR = 'CVO/PERSONS/PATCH_PERSON_ERROR';

export const DELETE_PERSON = 'CVO/PERSONS/DELETE_PERSON';
export const DELETE_PERSON_SUCCESS = 'CVO/PERSONS/DELETE_PERSON_SUCCESS';
export const DELETE_PERSON_ERROR = 'CVO/PERSONS/DELETE_PERSON_ERROR';

export const PATCH_PERSON_GROUPS = 'CVO/PERSONS/PATCH_PERSON_GROUPS';
export const PATCH_PERSON_GROUPS_SUCCESS = 'CVO/PERSONS/PATCH_PERSON_GROUPS_SUCCESS';
export const PATCH_PERSON_GROUPS_ERROR = 'CVO/PERSONS/PATCH_PERSON_GROUPS_ERROR';